name: workflow_with_security_scan

on:
  workflow_dispatch:
    
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout
      uses: actions/checkout@v2

  SecurityScanResults:
    needs: build
    runs-on: ubuntu-latest
    name: ServiceNow DevOps Security Results

    steps:
      - name: ServiceNow DevOps Security Results
        uses: ServiceNow/servicenow-devops-security-result@v2.0.0
        with:
          devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER }}
          devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD }}
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          context-github: ${{ toJSON(github) }}
          job-name: "ServiceNow DevOps Security Results"
          security-result-attributes: '{"scanner":"Veracode","applicationName":"VeraDemo10","buildVersion":"jenkins-Veracode with Step-27"}'


